function combinations = A3_combineConfigs(iPeriods, searchRanges, ns, ...
     nReframes, VBSEnables, FMEEnables, FastMEs)
    [iperiodsGrid, searchRangeGrid, nGrid, nrefGrid, ...
        VBSEnableGrid, FMEEnableGrid, FastMEGrid] = ndgrid(iPeriods, searchRanges, ns, ...
        nReframes, VBSEnables, FMEEnables, FastMEs);

    combinations = [iperiodsGrid(:), searchRangeGrid(:), nGrid(:), ... 
        nrefGrid(:), VBSEnableGrid(:), FMEEnableGrid(:), FastMEGrid(:)];
    % 
    % combinations = [];
    % for i = 1:length(iPeriods)
    %     for j = 1:length(searchRanges)
    %         for k = 1:length(ns)
    %             for l = 1:length(blockSizes)
    %                 for m = 1:length(nReframes)
    %                     for n = 1: length(VBSEnables)
    %                         for o = 1:length(FMEEnables)
    %                             for p = 1:length(FastMEs)
    %                                 combinations = [combinations; ...
    %                                     iPeriods(i), ...
    %                                     searchRanges(j), ...
    %                                     ns(k), ...
    %                                     blockSizes(l), ...
    %                                     nReframes(m), ...
    %                                     VBSEnables(n), ...
    %                                     FMEEnables(o), ...
    %                                     FastMEs(p)];
    %                             end
    %                         end
    %                     end
    %                 end                   
    %             end
    %         end
    %     end
    % end
end
